# Generated by Django 5.2.4 on 2025-08-14 18:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RePo-SUDOE-AI Chat Session',
                'verbose_name_plural': 'RePo-SUDOE-AI Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'RePo-SUDOE-AI Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='frontend.chatsession')),
            ],
            options={
                'verbose_name': 'RePo-SUDOE-AI Chat Message',
                'verbose_name_plural': 'RePo-SUDOE-AI Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('receptor', 'Receptor'), ('ligand', 'Ligand'), ('pose', 'Correct Pose')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='uploaded', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RePo-SUDOE-AI Uploaded File',
                'verbose_name_plural': 'RePo-SUDOE-AI Uploaded Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DockingSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remove_non_protein_atoms', models.BooleanField(default=False)),
                ('additional_parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('binding_affinity', models.FloatField(blank=True, null=True)),
                ('results_data', models.JSONField(blank=True, default=dict)),
                ('output_files', models.JSONField(blank=True, default=list)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docking_simulations', to=settings.AUTH_USER_MODEL)),
                ('ligand_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligand_simulations', to='frontend.uploadedfile')),
                ('pose_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pose_simulations', to='frontend.uploadedfile')),
                ('receptor_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor_simulations', to='frontend.uploadedfile')),
            ],
            options={
                'verbose_name': 'RePo-SUDOE-AI Docking Simulation',
                'verbose_name_plural': 'RePo-SUDOE-AI Docking Simulations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DockingPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_number', models.PositiveIntegerField()),
                ('binding_score', models.FloatField()),
                ('rmsd', models.FloatField(blank=True, null=True)),
                ('coordinates', models.JSONField(default=dict)),
                ('pdb_content', models.TextField(blank=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='frontend.dockingsimulation')),
            ],
            options={
                'verbose_name': 'RePo-SUDOE-AI Docking Pose',
                'verbose_name_plural': 'RePo-SUDOE-AI Docking Poses',
                'ordering': ['binding_score'],
                'unique_together': {('simulation', 'pose_number')},
            },
        ),
    ]
