# Generated by Django 5.2.4 on 2025-08-21 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_update_drug_terminology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockingsimulation',
            name='drug_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_simulations', to='frontend.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('receptor', 'Receptor'), ('drug', 'Drug'), ('pose', 'Correct Pose')], max_length=10),
        ),
    ]
